#!/usr/bin/env bash
# Install nginx webserver
apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
cat <<EOF > /etc/nginx/sites-available/default
server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location / {
        root /var/www/html;
	index index.html;
     }
}
EOF

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

service nginx restart
