#!/usr/bin/env bash

# Define the target URL where /redirect_me should redirect to
TARGET_URL="https://onsomu.tech/new-page"

# Create an Nginx configuration file for the redirection
echo "server {
    listen 80;
    onsomu.tech;

    location /redirect_me {
        return 301 onsomu.tech;
    }

}" | sudo tee /etc/nginx/sites-available/redirect_me.conf

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# If the configuration test is successful, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo systemctl reload nginx
else
    echo "Nginx configuration test failed. Please check your configuration."
fi
