#!/usr/bin/env bash

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page with the string "This page is not here"
echo "This page is not here" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page and return a 404 error code
config_string="error_page 404 /404.html;\nlocation = /404.html {\n    root /var/www/html;\n    internal;\n}"
sudo sed -i "/server_name _;/a $config_string" /etc/nginx/sites-enabled/default

# Reload Nginx to apply the changes
sudo systemctl reload nginx
