#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo systemctl reload nginx
