#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart

config_file="/etc/nginx/nginx.conf"
header_key="X-Served-By"

# Get the hostname of the server
hostname=$(hostname)
if ! sudo grep -q "add_header $header_key" $config_file; then
    # Define the custom header value with the hostname
    header_value="$hostname"
    # Create the add_header directive
    header="add_header $header_key \"$header_value\";"
    
    # Use sed to append the header configuration to the end of the http block
    sudo sed -i "/http {/ a $header" $config_file
    # Restart Nginx to apply the configuration changes
    sudo service nginx restart
fi
