#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
# edit config file
config_snippet="
frontend app_frontend
        bind *:80
        mode http
        default_backend app_backend
backend app_backend
        balance roundrobin
        server 339356-web-01 100.25.166.183 check
        server 339356-web-02 100.25.146.150 check"
echo "$config_snippet" | sudo tee -a /etc/haproxy/haproxy.cfg.original_copy

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
