#!/usr/bin/env bash
# This script parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays this data from the greatest to the lowest
#   number of occurrences.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
