#!/usr/bin/env bash
# Repeat task 1 with 7 or fewer lines
pkill apache2
sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0644 /etc/nginx/nginx.conf
su nginx -c "service nginx start"
