#!/usr/bin/env bash
# Fixes the container so that Nginx is running as the nginx use
service nginx stop
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx start
